apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server-red
  labels:
    app: red
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: red
    spec:
      containers:
      - image: pramodshehan/server-red:0.1
        name: server-red
        imagePullPolicy: IfNotPresent
        ports:
         - name: http
           containerPort: 8060
