apiVersion: v1
kind: Service
metadata:
  name: server-red
  labels:
    app: red
spec:
  ports:
  - port: 8060
    protocol: TCP
    targetPort: 8060    
  selector:
    app: red
  sessionAffinity: None
  type: NodePort

