apiVersion: v1
kind: Service-blue
metadata:
  name: server
  labels:
    app: blue
spec:
  ports:
  - port: 8070
    protocol: TCP
    targetPort: 8070    
  selector:
    app: blue
  sessionAffinity: None
  type: NodePort

